- pipeline.id: game_record_pipeline
  path.config: "/usr/share/logstash/pipeline/gameRecord.conf"
  pipeline.workers: 1
  queue.type: persisted

- pipeline.id: purchase_record_pipeline
  path.config: "/usr/share/logstash/pipeline/hemaiRecord.conf"
  pipeline.workers: 1
  queue.type: persisted


- pipeline.id: gift_reward_pipeline
  path.config: "/usr/share/logstash/pipeline/gift_reward.conf"
  pipeline.workers: 1
  queue.type: persisted
